{% set name = "checkmake" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mrtazz/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 37f14cbf37135e3c7507b990234c4fdfd9643d4227924541db901b84a66dcd14

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses
    - make
    - pandoc

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/mrtazz/{{ name }}
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Linter/analyzer for Makefiles
  dev_url: https://github.com/mrtazz/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
