{% set name = "checkmake" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mrtazz/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 450412ba6500ef7c4c8a0150a5e1a3d2e76591ce9f37609bcbd5508298ad9bef

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses
    - make
    - pandoc

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/mrtazz/{{ name }}
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Linter/analyzer for Makefiles
  dev_url: https://github.com/mrtazz/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
