{% set name = "checkmake" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mrtazz/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4c45c5eda4d22b1b603cad7836805927f047ca5e3a88fbefbbf1a636c87495b7

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses
    - make
    - pandoc

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/mrtazz/{{ name }}
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Linter/analyzer for Makefiles
  dev_url: https://github.com/mrtazz/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
